# Generated by Django 5.2.6 on 2025-10-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_applicants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of applicants allowed', null=True),
        ),
    ]
