# Generated by Django 5.2.6 on 2025-10-21 21:56

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_max_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF, DOC, DOCX supported)', null=True, upload_to=jobs.models.resume_upload_path),
        ),
    ]
