# Generated by Django 5.2.6 on 2025-10-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='analysis_completed',
            field=models.BooleanField(default=False, help_text='Whether resume analysis has been completed'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='analysis_date',
            field=models.DateTimeField(blank=True, help_text='When the resume analysis was last performed', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_analysis_data',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed resume analysis results'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_analysis_score',
            field=models.FloatField(default=0.0, help_text='Resume match score (0-100)'),
        ),
    ]
