# Generated by Django 5.2.6 on 2025-11-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_analysis_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_experience_years',
            field=models.IntegerField(default=0, help_text='Minimum years of experience required'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_education',
            field=models.JSONField(blank=True, default=list, help_text='List of required education qualifications'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required technical/professional skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_soft_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required soft skills'),
        ),
    ]
