# Generated by Django 5.2.6 on 2025-11-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_min_experience_years_job_required_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether the job is archived'),
        ),
    ]
