# Generated by Django 5.2.6 on 2025-11-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archive_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time to automatically archive this job', null=True),
        ),
    ]
